### ISSUE TITLE
Exception thrown if Ordinal in DICOM checks is -1

### ISSUE THREAD

**Issue by JonathanTripp** [microsoft/InnerEye-Gateway#19]
The documentation for DICOM RegexConstraint, OrderedNNNConstraint and StringContainsConstraint checks says that it -1 is used as the ordinal then all tag values are considered. Unfortunately this throws an exception in dataSet.GetValue<string>(Index.DicomTag, Ordinal); because the API for fo-dicom has changed.

**Comment by dumbledad** [comment]
[AB#4120](https://innereye.visualstudio.com/InnerEye/_workitems/edit/4120)
