### ISSUE TITLE
Enable warnings as errors and add static analysis

### ISSUE THREAD

**Issue by javier-alvarez** [microsoft/InnerEye-Gateway#3]

**Comment by JonathanTripp** [comment]
This has partially been done. All the project files should contain:

   <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

But, in .editorconfig a lot of warnings have been disabled.
